version: "3.9"
services:
  mysql:
      environment:
          - MYSQL_DATABASE=root
          - MYSQL_ROOT_PASSWORD=root
      command:
         - --table_definition_cache=100
         - --performance_schema=0
         - --default-authentication-plugin=mysql_native_password
         - --innodb_use_native_aio=0
      volumes:
          - /root/init:/docker-entrypoint-initdb.d
          - /root/databases:/var/lib/mysql
      container_name: mysql1
      ports:
          - "3306:3306"
      image: mysql

volumes:
      databases: {}
